name: 'Build NextJs'
description: 'Build NextJs Project'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/setup-nodejs
    - uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - run: npm run build
      shell: sh
