name: 'Build NextJs'
description: 'Build NextJs Project'
inputs:
  NEXT_PUBLIC_FIREBASE_API_KEY:
    required: true
    description: 'NEXT_PUBLIC_FIREBASE_API_KEY'
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
    required: true
    description: 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN'
  NEXT_PUBLIC_FIREBASE_PROJECT_ID:
    required: true
    description: 'NEXT_PUBLIC_FIREBASE_PROJECT_ID'
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
    required: true
    description: 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET'
  NEXT_PUBLIC_FIREBASE_APP_ID:
    required: true
    description: 'NEXT_PUBLIC_FIREBASE_APP_ID'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/setup-nodejs
    - uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - run: npm run build
      shell: sh
      env:
        NEXT_PUBLIC_FIREBASE_API_KEY: ${{ inputs.NEXT_PUBLIC_FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ inputs.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ inputs.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ inputs.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${{ inputs.NEXT_PUBLIC_FIREBASE_APP_ID }}
