name: PR Checks

on:
  pull_request:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-nodejs
      - run: npm run lint
